package vs.gui;

import vs.App;
import vs.core.candidates.Candidate;
import vs.core.candidates.Candidates;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.util.ArrayList;

public class Voting {
    private JPanel panel;

    public Voting(App app) {
        panel.setOpaque(false);
        try {
            ArrayList<Candidate> candidates = Candidates.getCandidates();
            int desiredWidth = (app.getWidth() / (candidates.size() + 1) - (candidates.size() * 10));
            for (Candidate c : candidates) {
                CandidateView cv = new CandidateView(app, c, desiredWidth);
                panel.add(cv.getPanel());
            }
            CandidateView cvBlank = new CandidateView(app, desiredWidth);
            panel.add(cvBlank.getPanel());
        } catch (SQLException | ClassNotFoundException e) {
            new ErrorView(e);
        }
    }

    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
